### ISSUE TITLE
Bad plural key name 'few'

### ISSUE THREAD

**Issue by Spider84** [lvgl/lv_i18n#58]
```
ru-RU:
  nitorgen_remainder:
    one: Запас азота %u литр
    few: Запас азота %u литра
    many: Запас азота %u литров
```
>Error in src/translations/en-GB.yml
Bad plural key name 'few' in 'nitrgen_remainder'
Allowed values are: one, other

Why?
