### ISSUE TITLE
Unoptimized compile of yml translation files may create zero size arrays

### ISSUE THREAD

**Issue by vortex-surfer** [lvgl/lv_i18n#75]
When compiling yml translation files that do not contain any plural strings
```
en-GB:
  s_en_only: english only
  s_translated: s translated
  s_untranslated: ~
ru-RU:
  s_en_only: ~
  s_translated: s переведено
  s_untranslated: ~
```
 to lv_i18n.c/h file without optimization enabled, the created source file accomodates zero size arrays that cannot be compiled with the compiler option `-Wpedantic` enabled:
```
...
#ifndef LV_I18N_OPTIMIZE

static const char * singular_idx[] = {
"This is a new text",
"s_en_only",
"s_translated",
"s_untranslated",

};

static const char * plural_idx[] = {

};

#endif
...
```
The patch below adds a null pointer to the array when the translation memory does not contain any strings:
[0001-Avoid-zero-size-array-creation.patch](https://github.com/user-attachments/files/18375590/0001-Avoid-zero-size-array-creation.patch)
```
...
#ifndef LV_I18N_OPTIMIZE

static const char * singular_idx[] = {
    "This is a new text",
    "s_en_only",
    "s_translated",
    "s_untranslated",

};

static const char * plural_idx[] = {
    NULL,
};

#endif
...
```
